name: comp version
on: 
   repository_dispatch:
    types: [my-event]
   push:
   
jobs:
  updateVersion:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: create a branch
        run: |
          newversion=$(curl -H 'Authorization: token ${{ secrets.MY_ORG }}' --silent "https://api.github.com/repos/selftestdisco/searchgitusers/releases/latest" | grep '"name":' | sed -E 's/.*"([^"]+)".*/\1/' )
          echo $newversion
          sed  -i -e "/version\":/s/[0-9]*\.[0-9]*\.[0-9]*/${newversion}/" package.json
          head -5 package.json
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v3
        with:
          token: ${{ secrets.MY_ORG }}
          commit-message: "Release updated"
          delete-branch: true
          branch: "newbranch"
          base: "master"
          body: 
            To show PR
          title: "Auto PR"
          
          
          
           
