name: comp version
on: 
    push:
jobs:
  initiator:
    runs-on: ubuntu-latest
    steps:
    - name: Setup Python
      uses: actions/setup-python@v4.3.0
    - name: compare version
      run:   python3 --version
    - run: |
        cat << EOF >>compare.py
        import sys
        version1 = sys.argv[1]
        #print("Deepak: ",version1)
        version2 = sys.argv[2]
        class Solution:
            def compareVersion(self, version1: str, version2: str) -> int:
                nums1 = version1.split('.')
                print("Deepak: ",nums1)
                nums2 = version2.split('.')
                print("Deepak: ",nums2)
                n1, n2 = len(nums1), len(nums2)

                # compare versions
                for i in range(max(n1, n2)):
                    i1 = int(nums1[i]) if i < n1 else 0
                    i2 = int(nums2[i]) if i < n2 else 0
                    if i1 != i2:
                        return 1 if i1 > i2 else -1

                # the versions are equal
                return 0 
        EOF

    - run:   python3 compare.py "2.0.1" "2.1.1" > ans.txt
    - run: |
           cat ans.txt
           echo Hello
           cat compare.py
