name: comp version
on: 
   repository_dispatch:
    types: [my-event]
   push:
   
jobs:
  updateVersion:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: create a branch
        run: |
          git checkout -b newbranch
          newversion=$(curl -H 'Authorization: token ${{ secrets.MY_ORG }}' --silent "https://api.github.com/repos/selftestdisco/searchgitusers/releases/latest" | grep '"name":' | sed -E 's/.*"([^"]+)".*/\1/' )
          echo $newversion
      - name: Update package.json
        run: |
          sed -i 's|"\version\": "\*"\,|\"verson\": "\$newversion\",|' package.json
          cat package.json
        
        
